[package]
name = "gsr_test"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
ethers = { version = "1" }
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12.5", features = ["json"] }
hex = "0.4"
