name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        profile: minimal
        toolchain: stable

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-registry-

    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-index-

    - name: Build and test
      run: |
        cargo build --verbose
        cargo test --verbose

    - name: Run application
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
        NETWORK: ${{ secrets.NETWORK }}
        BLOCK_NUMBER: ${{ secrets.BLOCK_NUMBER }}
      run: |
        cargo run --release
